### ISSUE TITLE
what is the ternoa mainnet chain wallet connect v2 ?

### ISSUE THREAD

**Issue by Nzenou** [capsule-corp-ternoa/ternoa-wallet#1]
In the different doc about the wallet we can find  : 
const TERNOA_ALPHANET_CHAIN = "ternoa:18bcdb75a0bba577b084878db2dc2546";

const requiredNamespaces = {
  ternoa: {
    chains: [TERNOA_ALPHANET_CHAIN],
    events: ["event_test"],
    methods: ["sign_message"],
  },
};

to connect the ternoa wallet to the alphanet  chain, is it possible to have the code to be connected to the mainnet 

thanks a lot

**Comment by dhammani** [comment]
Hi @Nzenou, to connect the wallet to the Mainnet, you can use `TERNOA_MAINNET_CHAIN=ternoa:6859c81ca95ef624c9dfe4dc6e3381c3`

**Comment by Nzenou** [comment]
Thanks a lot !!

**Comment by dhammani** [comment]
Happy to help!
