### ISSUE TITLE
Issue to connect 

### ISSUE THREAD

**Issue by Nzenou** [capsule-corp-ternoa/ternoa-wallet#5]
Hello guys, 

I have a problem when I try to connect to my dapp : 
{context: 'client'} "Cannot read properties of undefined (reading 'MISSING_OR_INVALID')"

using the connect function of the ternoa-wallet : 
const connect = useCallback(
    async (pairing) => {
      if (typeof store.client === undefined) {
        throw new Error("WalletConnect is not initialized");
      }
      try {
        console.log("test4")
        console.log(store.client,'store.client')
        console.log(pairing,'pairing')
        console.log(requiredNamespaces,'requiredNamespaces')
        const { uri, approval } = await store.client.connect({
          pairingTopic: pairing?.topic,
          requiredNamespaces: requiredNamespaces,
        });
        console.log(uri,'uri')

        if (uri) {
          QRCodeModal.open(uri);
        }
        const session = await approval();
        onSessionConnected(session);
      } catch (e) {
        console.error(e);
      } finally {
        QRCodeModal.close();
      }
    },
    [store.client, onSessionConnected]
  );
  
  the issue appear at the line :  const { uri, approval } = await store.client.connect 
  
I don't understand why because I have the object client and the property  connect inside it, also the issue appear just online, when I using this code in local I have no problem, the Qr code display and I can connect 

If someone have a workaround it will help me a lot 

Thanks in advance

**Comment by lautaro-osacar** [comment]
Hi @Nzenou, did you checked what you have in `requiredNamespaces` on the environment that is not working?

**Comment by Nzenou** [comment]
I have that : 
const TERNOA_ALPHANET_CHAIN = "ternoa:18bcdb75a0bba577b084878db2dc2546";
const TERNOA_MAINNET_CHAIN = "ternoa:6859c81ca95ef624c9dfe4dc6e3381c3";

const TERNOA_CONNECT = process.env.NEXT_PUBLIC_PROD !=0 ? TERNOA_MAINNET_CHAIN : TERNOA_ALPHANET_CHAIN;

const requiredNamespaces = {
  ternoa: {
    chains: [TERNOA_CONNECT],
    events: ["event_test"],
    methods: ["sign_message"],
  },
};

and currently using the prod one, so this one : ternoa:6859c81ca95ef624c9dfe4dc6e3381c3

**Comment by lautaro-osacar** [comment]
Have you checked how you are initializing the wallet connect client? What relay URL are you using?

**Comment by Nzenou** [comment]
I am using this one : 
 const _client = await Client.init({
        relayUrl: "wss://wallet-connectrelay.ternoa.network/",
        projectId: "e8f6f7d41ff88cd96a21ce580f018401",
        metadata: DEFAULT_APP_METADATA,
      });

**Comment by Nzenou** [comment]
@elvid help me on the issue, 

you need to add that to the package.json : 

"resolutions": {
    "@walletconnect/sign-client": "2.0.0-beta.100",
    "@walletconnect/core": "2.0.0-beta.100",
    "@walletconnect/types": "2.0.0-beta.100",
    "@walletconnect/utils": "2.0.0-beta.100",
    "@walletconnect/legacy-modal": "2.0.0-beta.100"
  },
